### ISSUE TITLE
5.5中代码问题

### ISSUE THREAD

**Issue by cyxbit** [caicloud/tensorflow-tutorial#51]
在运行5.5中mnist_train.py的例程时，出现报错

runfile('C:/Users/Chen Yanxi/deeplearning_pythoncode/2017.7/mnist_train_55.py', wdir='C:/Users/Chen Yanxi/deeplearning_pythoncode/2017.7')
Reloaded modules: mnist_inference_55, mnist_train_55
Extracting /tmp/data\train-images-idx3-ubyte.gz
Extracting /tmp/data\train-labels-idx1-ubyte.gz
Extracting /tmp/data\t10k-images-idx3-ubyte.gz
Extracting /tmp/data\t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):

  File "<ipython-input-37-dbfd5df990e3>", line 1, in <module>
    runfile('C:/Users/Chen Yanxi/deeplearning_pythoncode/2017.7/mnist_train_55.py', wdir='C:/Users/Chen Yanxi/deeplearning_pythoncode/2017.7')

  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Chen Yanxi/deeplearning_pythoncode/2017.7/mnist_train_55.py", line 84, in <module>
    tf.app.run()

  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))

  File "C:/Users/Chen Yanxi/deeplearning_pythoncode/2017.7/mnist_train_55.py", line 81, in main
    train(mnist)

  File "C:/Users/Chen Yanxi/deeplearning_pythoncode/2017.7/mnist_train_55.py", line 43, in train
    variables_averages_op = variable_averages.apply(tf.trainable_variables())

  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\tensorflow\python\training\moving_averages.py", line 367, in apply
    colocate_with_primary=True)

  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\tensorflow\python\training\slot_creator.py", line 113, in create_slot
    return _create_slot_var(primary, val, "", validate_shape, None, None)

  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\tensorflow\python\training\slot_creator.py", line 66, in _create_slot_var
    validate_shape=validate_shape)

  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)

  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)

  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)

  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)

  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 664, in _get_single_variable
    name, "".join(traceback.format_list(tb))))

ValueError: Variable layer1/weights/ExponentialMovingAverage/ already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()
  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\ProgramData\Anaconda2\envs\num2\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)

请问应如何修改关于变量名的设置呢，谢谢。

**Comment by perhapszzy** [comment]
请确认一下tensorflow的版本和python的版本，如果版本都能对上，那么应该是可以正常运行的

**Comment by ScorpioCPH** [comment]
@cyxbit ping.

**Comment by zhengzhuangqiang** [comment]
我也遇到了，楼主怎么解决的？

**Comment by tangdouzi** [comment]
解决了吗？我也出现这个问题。。我的1.50版本，怎么修改？
